swagger: '2.0'
info:
  description: Swagger doc for vehicle management api
  version: '1.0.0'
  title: Vehicle Enrollment
  contact:
    name: Data Marketplace
    email: marketplace@toyotaconnected.com
  license:
    name: Data Marketplace
    url: 'https://toyotaconnected.com'
host: dev-vehicle-management.tcmobility.net
basePath: /
paths:
  /v1/vehicles/enrollments:
    post:
      tags:
        - Vehicle Enrollment
      summary: 'Add one vehicle to a product subscription '
      description: Add one vehicle to a product subscription
      operationId: enrollUsingPOST
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: x-id-token
          in: header
          description: x-id-token
          required: true
          type: string
        - in: body
          name: enrollRequest
          description: enrollRequest
          required: true
          schema:
            $ref: '#/definitions/EnrollRequest'
      responses:
        '200':
          description: Request received successfully.
          schema:
            $ref: '#/definitions/ResponseEntity'
        '201':
          description: Created
        '400':
          description: Bad request
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
        '500':
          description: Internal server error
  /v1/vehicles/enrollments/bulk:
    post:
      tags:
        - Vehicle Enrollment
      summary: 'Add multiple vehicles to a product subscription '
      description: Add multiple vehicles to a product subscription
      operationId: bulkEnrollUsingPOST
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: x-id-token
          in: header
          description: x-id-token
          required: true
          type: string
        - in: body
          name: bulkRequest
          description: bulkRequest
          required: true
          schema:
            $ref: '#/definitions/BulkEnrollRequest'
      responses:
        '200':
          description: Request received successfully.
          schema:
            $ref: '#/definitions/RequestStatus'
        '201':
          description: Created
        '400':
          description: Bad request
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
        '500':
          description: Internal server error
definitions:
  BulkEnrollRequest:
    type: object
    properties:
      actions:
        type: array
        example: '[{"action":"CREATE","products":[{"productId":"8270e427-575b-4fd6-9fa5-29536a717605","vinList":["APITESTSK00000013","APITESTSK00000014","APITESTSK00000015","APITESTSK00000016"]},{"productId":"57f73311-72da-4634-a28b-1a7e48613d23","vinList":["APITESTSK00000013","APITESTSK00000014","APITESTSK00000015","APITESTSK00000016"]}]}]'
        description: actions of the BulkEnrollRequest
        items:
          $ref: '#/definitions/BulkEnrollRequestActions'
      subscriberId:
        type: string
        example: e7b937e1-f08c-43b7-b94a-b4ea7e0ab97c
        description: subscriberId of the BulkEnrollRequest
  BulkEnrollRequestActions:
    type: object
    properties:
      action:
        type: string
        enum:
          - CREATE
          - DELETE
      products:
        type: array
        items:
          $ref: '#/definitions/VehicleProducts'
  EnrollRequest:
    type: object
    properties:
      actions:
        type: array
        example: '[{"action":"CREATE","products":["ef7c6258-f824-4f9d-be59-115b8bb1070a","67861901-ae9b-4dd6-8b3a-9839c5194493"]},{"action":"CREATE","products":["a9c4756c-4003-4b6a-86de-719336ed1e2e","57f73311-72da-4634-a28b-1a7e48613d23"]}]'
        description: actions of the EnrollRequest
        items:
          $ref: '#/definitions/EnrollRequestActions'
      subscriberId:
        type: string
        example: ea4eeae7-1f0e-4407-9516-157405640636
        description: subscriberId of the EnrollRequest
      vin:
        type: string
        example: APITESTRJ99900005
        description: vin of the EnrollRequest
  EnrollRequestActions:
    type: object
    properties:
      action:
        type: string
        enum:
          - CREATE
          - DELETE
      products:
        type: array
        items:
          type: string
  RequestStatus:
    type: object
    properties:
      correlationId:
        type: string
        example: 67861901-ae9b-4dd6-8b3a-9839c5194493
        description: correlationId of the Products
      invalidVins:
        type: array
        example: '["APITESTSK00000014","APITESTSK00000016"]'
        description: invalidVins of the Products
        items:
          type: string
      status:
        type: string
        example: SUCCESS
        description: status of the Products
  ResponseEntity:
    type: object
    properties:
      body:
        type: object
      statusCode:
        type: string
        enum:
          - 100 CONTINUE
          - 101 SWITCHING_PROTOCOLS
          - 102 PROCESSING
          - 103 CHECKPOINT
          - 200 OK
          - 201 CREATED
          - 202 ACCEPTED
          - 203 NON_AUTHORITATIVE_INFORMATION
          - 204 NO_CONTENT
          - 205 RESET_CONTENT
          - 206 PARTIAL_CONTENT
          - 207 MULTI_STATUS
          - 208 ALREADY_REPORTED
          - 226 IM_USED
          - 300 MULTIPLE_CHOICES
          - 301 MOVED_PERMANENTLY
          - 302 FOUND
          - 302 MOVED_TEMPORARILY
          - 303 SEE_OTHER
          - 304 NOT_MODIFIED
          - 305 USE_PROXY
          - 307 TEMPORARY_REDIRECT
          - 308 PERMANENT_REDIRECT
          - 400 BAD_REQUEST
          - 401 UNAUTHORIZED
          - 402 PAYMENT_REQUIRED
          - 403 FORBIDDEN
          - 404 NOT_FOUND
          - 405 METHOD_NOT_ALLOWED
          - 406 NOT_ACCEPTABLE
          - 407 PROXY_AUTHENTICATION_REQUIRED
          - 408 REQUEST_TIMEOUT
          - 409 CONFLICT
          - 410 GONE
          - 411 LENGTH_REQUIRED
          - 412 PRECONDITION_FAILED
          - 413 PAYLOAD_TOO_LARGE
          - 413 REQUEST_ENTITY_TOO_LARGE
          - 414 URI_TOO_LONG
          - 414 REQUEST_URI_TOO_LONG
          - 415 UNSUPPORTED_MEDIA_TYPE
          - 416 REQUESTED_RANGE_NOT_SATISFIABLE
          - 417 EXPECTATION_FAILED
          - 418 I_AM_A_TEAPOT
          - 419 INSUFFICIENT_SPACE_ON_RESOURCE
          - 420 METHOD_FAILURE
          - 421 DESTINATION_LOCKED
          - 422 UNPROCESSABLE_ENTITY
          - 423 LOCKED
          - 424 FAILED_DEPENDENCY
          - 426 UPGRADE_REQUIRED
          - 428 PRECONDITION_REQUIRED
          - 429 TOO_MANY_REQUESTS
          - 431 REQUEST_HEADER_FIELDS_TOO_LARGE
          - 451 UNAVAILABLE_FOR_LEGAL_REASONS
          - 500 INTERNAL_SERVER_ERROR
          - 501 NOT_IMPLEMENTED
          - 502 BAD_GATEWAY
          - 503 SERVICE_UNAVAILABLE
          - 504 GATEWAY_TIMEOUT
          - 505 HTTP_VERSION_NOT_SUPPORTED
          - 506 VARIANT_ALSO_NEGOTIATES
          - 507 INSUFFICIENT_STORAGE
          - 508 LOOP_DETECTED
          - 509 BANDWIDTH_LIMIT_EXCEEDED
          - 510 NOT_EXTENDED
          - 511 NETWORK_AUTHENTICATION_REQUIRED
      statusCodeValue:
        type: integer
        format: int32
  VehicleProducts:
    type: object
    properties:
      productId:
        type: string
      vinList:
        type: array
        items:
          type: string
